# Simulation configuration (OpenFWI compatible)
nx: 70
nz: 70
dx: 10.0
nbc: 120
nt: 1000
dt: 0.001
freq: 15.0
isFS: false

coord:
  sx: 350.0    # 1 * dx
  sz: 10.0
  gx_start: 1
  gx_end: 70
  gx_step: 1
  gz_value: 10.0

