seed: 42
n_models: 100

model_types: [ layered, fault, dome, perlin ]

model_probabilities:
  layered: 1.0
  fault: 0.0
  dome: 0.0
  perlin: 0.0
# end model_probabilities

model_params:
  dx: 10.0
  dz: 10.0
  nx: 70
  nz: 70
  sigma: 0.75
  layered:
    n_layers_range: [ 3, 12 ]
    v_range: [ 1500, 4500 ]
    angle: 25.0
  fault:
    v_range: [3000, 3500]
    delta_v_range: [ 500, 1500 ]
    slope_range: [ 0.1, 0.5 ]
    offset_range: [ 15, 50 ]
    sigma: 0.75
  dome:
    center_range: [35, 50]
    radius_range: [15, 35]
    v_high_range: [2500, 4500]
    v_low_range: [1500, 2000]
    sigma: 0.75
  perlin:
    scale_range: [15.0, 65.0]
    v_range: [2500, 4500]
    contrast_range: [500, 1000]
    n_level_range: [6, 12]
    sigma: 0.75
# end model_params

transforms: [ rotate, stretch, inclusion, perlin_noise, add_crossline, swirl, piecewise_affine, displacement_field ]

transform_probabilities:
  rotate: 0.4
  stretch: 0.4
  inclusion: 0.4
  perlin_noise: 0.4
  add_crossline: 0.4
  swirl: 0.4
  piecewise_affine: 0.0
  displacement_field: 1.0
# end transform_probabilities

skimage_transform_prob: 0.0
skimage_transform_crop_ratio: 0.0

transform_params:
  rotate:
    angle_range: [-10, 10]
  stretch:
    scale_range: [1.0, 1.3]
  inclusion:
    radius_range: [5, 10]
    velocity_range: [1300, 2200]
    n_inclusions_range: [1, 5]
  perlin_noise:
    scale_range: [500, 550]
    amplitude: 150
    n_levels: [-1, -0.5, 0, 0.5, 1]
  add_crossline:
    thickness_range: [5, 15]
    velocity_range: [1300, 3000]
  swirl:
    center_range: [0, 70]
    strength_range: [3, 5]
    radius_range: [70, 100]
  piecewise_affine:
    grid_shape: [5, 5]
    displacement_sigma: 0.5
  displacement_field:
    max_displacement: 10.0
    smooth_sigma: 8.0
  # end piecewise_affine
# end transform_params

validation:
  min_v: 1000
  max_v: 5000
  zero_thresh: 0.01
  unique_thresh: 0.85
  entropy_thresh: 0.2
